/*
Navicat MySQL Data Transfer

Source Server         : haiyou项目数据库213
Source Server Version : 50520
Source Host           : 192.168.123.213:3310
Source Database       : haiyou

Target Server Type    : MYSQL
Target Server Version : 50520
File Encoding         : 65001

Date: 2015-01-26 11:16:31
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `bh_grid_column`
-- ----------------------------
DROP TABLE IF EXISTS `bh_grid_column`;
CREATE TABLE `bh_grid_column` (
  `grid_id` varchar(50) DEFAULT NULL,
  `description` varchar(100) DEFAULT '',
  `name` varchar(100) DEFAULT '',
  `index` varchar(100) DEFAULT '',
  `table_field` varchar(255) DEFAULT '',
  `align` varchar(10) DEFAULT 'center',
  `width` int(11) DEFAULT '80',
  `hidden` tinyint(4) DEFAULT '0',
  `sortable` tinyint(4) DEFAULT '0',
  `sort` tinyint(4) DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of bh_grid_column
-- ----------------------------
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_BasicUnitInfo', 'plantmatchkey', 'plantmatchkey', 'plantmatchkey', 'api_plant.plantmatchkey', 'center', '80', '1', '0', '1');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_BasicUnitInfo', '油田名称', 'factory_displayname', 'factory_displayname', 'api_plant.factory_displayname', 'center', '70', '0', '0', '4');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_BasicUnitInfo', '平台名称', 'set_displayname', 'set_displayname', 'api_plant.set_displayname', 'center', '70', '0', '0', '5');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_BasicUnitInfo', '系统名称', 'systemname', 'systemname', 'haiyou_basic_unitinfo.systemname', 'center', '130', '0', '0', '6');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_BasicUnitInfo', '设备类型', 'machine_type', 'machine_type', 'api_plant.machine_type', 'center', '70', '0', '0', '7');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_BasicUnitInfo', '压力容器(管线)编号', 'plant_displayid', 'plant_displayid', 'api_plant.plant_displayid', 'center', '100', '0', '0', '8');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_BasicUnitInfo', '压力容器(管线)名称', 'plant_displayname', 'plant_displayname', 'api_plant.plant_displayname', 'center', '100', '0', '0', '9');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_BasicUnitInfo', '投用日期', 'use_time', 'use_time', 'haiyou_basic_unitinfo.use_time', 'center', '100', '0', '0', '10');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_BasicUnitInfo', '记录日期', 'update_time', 'update_time', 'haiyou_basic_unitinfo.update_time', 'center', '100', '0', '0', '15');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_BasicUnitInfo', '操作压力MPa', 'operation_pressure', 'operation_pressure', 'haiyou_basic_unitinfo.operation_pressure', 'center', '80', '0', '0', '11');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_BasicUnitInfo', '操作温度℃', 'operation_warm', 'operation_warm', 'haiyou_basic_unitinfo.operation_warm', 'center', '80', '0', '0', '12');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_BasicUnitInfo', '介质', 'medium', 'medium', 'haiyou_basic_unitinfo.medium', 'center', '80', '0', '0', '13');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_BasicUnitInfo', 'id', 'id', 'id', 'haiyou_basic_unitinfo.id', 'center', '80', '1', '0', '2');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Pipe_Parameter', 'pipe_id', 'pipe_id', 'pipe_id', '', 'center', '80', '1', '0', '1');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Pipe_Parameter', '油田名称', 'factory_displayname', 'factory_displayname', 'api_plant.factory_displayname', 'center', '80', '1', '0', '2');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Pipe_Parameter', '平台名称', 'set_displayname', 'set_displayname', 'api_plant.set_displayname', 'center', '80', '1', '0', '3');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Pipe_Parameter', '系统名称', 'systemname', 'systemname', 'haiyou_basic_unitinfo.systemname', 'center', '80', '1', '0', '4');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Pipe_Parameter', '设备类型', 'machine_type', 'machine_type', 'api_plant.machine_type', 'center', '80', '1', '0', '5');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Pipe_Parameter', '压力容器(管线)编号', 'plant_displayid', 'plant_displayid', 'api_plant.plant_displayid', 'center', '80', '1', '0', '6');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Pipe_Parameter', '压力容器(管线)名称', 'plant_displayname', 'plant_displayname', 'api_plant.plant_displayname', 'center', '80', '1', '0', '7');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Pipe_Parameter', '部位编号', 'place_num', 'place_num', 'haiyou_container_parameters.place_num', 'center', '80', '1', '0', '8');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Pipe_Parameter', '部位名称', 'place_name', 'place_name', 'haiyou_container_parameters.place_name', 'center', '80', '0', '0', '10');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Pipe_Parameter', '部位分类', 'place_class', 'place_class', 'haiyou_container_parameters.place_class', 'center', '80', '0', '0', '9');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Pipe_Parameter', '操作压力MPa', 'operation_pressure', 'operation_pressure', 'haiyou_container_parameters.operation_pressure', 'center', '80', '0', '0', '11');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Pipe_Parameter', '操作温度℃', 'operation_warm', 'operation_warm', 'haiyou_container_parameters.operation_warm', 'center', '80', '0', '0', '12');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Pipe_Parameter', '直径mm', 'diameter', 'diameter', 'haiyou_container_parameters.diameter', 'center', '80', '0', '0', '13');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Pipe_Parameter', '材质', 'material', 'material', 'haiyou_container_parameters.material', 'center', '80', '0', '0', '14');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Pipe_Parameter', '长度（高度）mm', 'height', 'height', 'haiyou_container_parameters.height', 'center', '80', '0', '0', '15');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Pipe_Parameter', '建造壁厚mm', 'make_thick', 'make_thick', 'haiyou_container_parameters.make_thick', 'center', '80', '0', '0', '16');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Pipe_Parameter', '最小要求壁厚mm', 'min_thick', 'min_thick', 'haiyou_container_parameters.min_thick', 'center', '80', '0', '0', '17');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Pipe_Parameter', '腐蚀裕度mm', 'corrosion_degree', 'corrosion_degree', 'haiyou_container_parameters.corrosion_degree', 'center', '80', '0', '0', '18');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Pipe_Parameter', '工作介质', 'work_medium', 'work_medium', 'haiyou_container_parameters.work_medium', 'center', '80', '0', '0', '19');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Pipe_Parameter', '记录日期', 'updatetime', 'updatetime', 'haiyou_container_parameters.updatetime', 'center', '80', '0', '0', '20');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Container_Parameter', 'container_id', 'container_id', 'container_id', '', 'center', '80', '1', '0', '1');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Container_Parameter', '油田名称', 'factory_displayname', 'factory_displayname', 'api_plant.factory_displayname', 'center', '80', '1', '0', '2');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Container_Parameter', '平台名称', 'set_displayname', 'set_displayname', 'api_plant.set_displayname', 'center', '80', '1', '0', '3');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Container_Parameter', '系统名称', 'systemname', 'systemname', 'haiyou_basic_unitinfo.systemname', 'center', '80', '1', '0', '4');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Container_Parameter', '设备类型', 'machine_type', 'machine_type', 'api_plant.machine_type', 'center', '80', '1', '0', '5');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Container_Parameter', '压力容器(管线)编号', 'plant_displayid', 'plant_displayid', 'api_plant.plant_displayid', 'center', '80', '1', '0', '6');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Container_Parameter', '压力容器(管线)名称', 'plant_displayname', 'plant_displayname', 'api_plant.plant_displayname', 'center', '80', '1', '0', '7');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Container_Parameter', '部位编号', 'place_num', 'place_num', 'haiyou_container_parameters.place_num', 'center', '80', '1', '0', '8');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Container_Parameter', '部位名称', 'place_name', 'place_name', 'haiyou_container_parameters.place_name', 'center', '80', '0', '0', '10');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Container_Parameter', '部位分类', 'place_class', 'place_class', 'haiyou_container_parameters.place_class', 'center', '80', '0', '0', '9');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Container_Parameter', '操作压力MPa', 'operation_pressure', 'operation_pressure', 'haiyou_container_parameters.operation_pressure', 'center', '80', '0', '0', '11');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Container_Parameter', '操作温度℃', 'operation_warm', 'operation_warm', 'haiyou_container_parameters.operation_warm', 'center', '80', '0', '0', '12');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Container_Parameter', '直径mm', 'diameter', 'diameter', 'haiyou_container_parameters.diameter', 'center', '80', '0', '0', '13');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Container_Parameter', '材质', 'material', 'material', 'haiyou_container_parameters.material', 'center', '80', '0', '0', '14');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Container_Parameter', '长度（高度）mm', 'height', 'height', 'haiyou_container_parameters.height', 'center', '80', '0', '0', '15');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Container_Parameter', '建造壁厚mm', 'make_thick', 'make_thick', 'haiyou_container_parameters.make_thick', 'center', '80', '0', '0', '16');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Container_Parameter', '最小要求壁厚mm', 'min_thick', 'min_thick', 'haiyou_container_parameters.min_thick', 'center', '80', '0', '0', '17');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Container_Parameter', '腐蚀裕度mm', 'corrosion_degree', 'corrosion_degree', 'haiyou_container_parameters.corrosion_degree', 'center', '80', '0', '0', '18');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Container_Parameter', '工作介质', 'work_medium', 'work_medium', 'haiyou_container_parameters.work_medium', 'center', '80', '0', '0', '19');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_Container_Parameter', '记录日期', 'updatetime', 'updatetime', 'haiyou_container_parameters.updatetime', 'center', '80', '0', '0', '20');
INSERT INTO `bh_grid_column` VALUES ('KnowledLib_KnowlebFiles', 'plantmatchkey', 'plantmatchkey', 'plantmatchkey', '', 'center', '80', '1', '0', '1');
INSERT INTO `bh_grid_column` VALUES ('KnowledLib_KnowlebFiles', '油田名称', 'factory_displayname', 'factory_displayname', '', 'center', '70', '0', '0', '2');
INSERT INTO `bh_grid_column` VALUES ('KnowledLib_KnowlebFiles', '平台名称', 'set_displayname', 'set_displayname', '', 'center', '70', '0', '0', '3');
INSERT INTO `bh_grid_column` VALUES ('KnowledLib_KnowlebFiles', '系统名称', 'systemname', 'systemname', '', 'center', '100', '0', '0', '4');
INSERT INTO `bh_grid_column` VALUES ('KnowledLib_KnowlebFiles', '设备类型', 'machine_type', 'machine_type', '', 'center', '70', '0', '0', '5');
INSERT INTO `bh_grid_column` VALUES ('KnowledLib_KnowlebFiles', '压力容器(管线)编号', 'plant_displayid', 'plant_displayid', '', 'center', '100', '0', '0', '6');
INSERT INTO `bh_grid_column` VALUES ('KnowledLib_KnowlebFiles', '压力容器(管线)名称', 'plant_displayname', 'plant_displayname', '', 'center', '100', '0', '0', '7');
INSERT INTO `bh_grid_column` VALUES ('KnowledLib_KnowlebFiles', '文件分类', 'parentfilename', 'filename', '', 'center', '70', '0', '0', '8');
INSERT INTO `bh_grid_column` VALUES ('KnowledLib_KnowlebFiles', '文件子类', 'filename', 'childfilename', '', 'center', '70', '0', '0', '9');
INSERT INTO `bh_grid_column` VALUES ('KnowledLib_KnowlebFiles', '文件名称', 'title', 'title', '', 'center', '70', '0', '0', '10');
INSERT INTO `bh_grid_column` VALUES ('KnowledLib_KnowlebFiles', '上传人', 'uploadusername', 'uploadusername', '', 'center', '60', '0', '0', '11');
INSERT INTO `bh_grid_column` VALUES ('KnowledLib_KnowlebFiles', '上传日期', 'uploadtime', 'uploadtime', '', 'center', '100', '0', '0', '12');
INSERT INTO `bh_grid_column` VALUES ('KnowledLib_KnowlebFiles', 'id', 'id', 'id', '', 'center', '80', '1', '0', '13');
INSERT INTO `bh_grid_column` VALUES ('KnowledLib_KnowlebFiles', 'filepath', 'filepath', '', '', 'center', '80', '1', '0', '13');
INSERT INTO `bh_grid_column` VALUES ('Knowled_KnowledTestCase', '油田名称', 'factory_displayname', 'factory_displayname', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Knowled_KnowledTestCase', '平台名称', 'set_displayname', 'set_displayname', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Knowled_KnowledTestCase', '系统名称', 'systemname', 'systemname', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Knowled_KnowledTestCase', '设备类型', 'machine_type', 'machine_type', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Knowled_KnowledTestCase', '压力容器(管线)编号', 'plant_displayid', 'plant_displayid', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Knowled_KnowledTestCase', '压力容器(管线)名称', 'plant_displayname', 'plant_displayname', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Knowled_KnowledTestCase', '上次检验日期', '', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Knowled_KnowledTestCase', '下次检验日期', '', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Knowled_KnowledTestCase', '更新日期', '', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('RegionForConsequence', '油田名称', 'factory_displayname', 'factory_displayname', '', 'center', '80', '0', '0', '2');
INSERT INTO `bh_grid_column` VALUES ('RegionForConsequence', '平台名称', 'set_displayname', 'set_displayname', '', 'center', '80', '0', '0', '3');
INSERT INTO `bh_grid_column` VALUES ('RegionForConsequence', '后果区域集合', 'factory_displayname', 'factory_displayname', '', 'center', '80', '0', '0', '4');
INSERT INTO `bh_grid_column` VALUES ('RegionForConsequence', '后果区域名称', 'factory_displayname', 'factory_displayname', '', 'center', '80', '0', '0', '5');
INSERT INTO `bh_grid_column` VALUES ('RegionForConsequence', 'plantmatchkey', 'plantmatchkey', 'plantmatchkey', '', 'center', '80', '1', '0', '1');
INSERT INTO `bh_grid_column` VALUES ('RegionForConsequence', '分类', 'class', 'class', '', 'center', '80', '0', '0', '6');
INSERT INTO `bh_grid_column` VALUES ('RegionForCorrosion', 'plantmatchkey', 'plantmatchkey', 'plantmatchkey', '', 'center', '80', '1', '0', '1');
INSERT INTO `bh_grid_column` VALUES ('RegionForCorrosion', '油田名称', 'factory_displayname', 'factory_displayname', '', 'center', '80', '0', '0', '2');
INSERT INTO `bh_grid_column` VALUES ('RegionForCorrosion', '平台名称', 'set_displayname', 'set_displayname', '', 'center', '80', '0', '0', '3');
INSERT INTO `bh_grid_column` VALUES ('RegionForCorrosion', '腐蚀回路集合', 'factory_displayname', 'factory_displayname', '', 'center', '80', '0', '0', '4');
INSERT INTO `bh_grid_column` VALUES ('RegionForCorrosion', '腐蚀回路名称', 'factory_displayname', 'factory_displayname', '', 'center', '80', '0', '0', '5');
INSERT INTO `bh_grid_column` VALUES ('RegionForIsolation', 'plantmatchkey', 'plantmatchkey', 'plantmatchkey', '', 'center', '80', '1', '0', '1');
INSERT INTO `bh_grid_column` VALUES ('RegionForIsolation', '油田名称', 'factory_displayname', 'factory_displayname', '', 'center', '80', '0', '0', '2');
INSERT INTO `bh_grid_column` VALUES ('RegionForIsolation', '平台名称', 'set_displayname', 'set_displayname', '', 'center', '80', '0', '0', '3');
INSERT INTO `bh_grid_column` VALUES ('RegionForIsolation', '分类', 'class', 'class', '', 'center', '100', '0', '0', '6');
INSERT INTO `bh_grid_column` VALUES ('RegionForIsolation', '可隔离区域集合', 'factory_displayname', 'factory_displayname', '', 'center', '80', '0', '0', '4');
INSERT INTO `bh_grid_column` VALUES ('RegionForIsolation', '可隔离区域名称', 'factory_displayname', 'factory_displayname', '', 'center', '80', '0', '0', '5');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_AccidentInfo', 'plantmatchkey', 'plantmatchkey', 'plantmatchkey', '', 'center', '80', '1', '0', '1');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_AccidentInfo', 'accident_id', 'accident_id', 'accident_id', '', 'center', '80', '1', '0', '2');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_AccidentInfo', '事故描述', 'consequence_analyse', 'consequence_analyse', '', 'center', '80', '0', '0', '3');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_AccidentInfo', '事故类型', 'accident_class', 'accident_class', '', 'center', '80', '0', '0', '4');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_AccidentInfo', '事故发生日期', 'accident_time', 'accident_time', '', 'center', '80', '0', '0', '5');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_AccidentInfo', '事故处理情况', 'accident_dispose', 'accident_dispose', '', 'center', '80', '0', '0', '6');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_AccidentInfo', '记录人', 'recordusername', 'recordusername', '', 'center', '80', '0', '0', '7');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_AccidentInfo', '记录日期', 'recordtime', 'recordtime', '', 'center', '80', '1', '0', '8');
INSERT INTO `bh_grid_column` VALUES ('KnowledLib_KnowledTestCase', 'plantmatchkey', 'plantmatchkey', 'plantmatchkey', '', 'center', '80', '1', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('KnowledLib_KnowledTestCase', '记录id', 'id', 'id', '', 'center', '80', '0', '0', '8');
INSERT INTO `bh_grid_column` VALUES ('KnowledLib_KnowledTestCase', '油田名称', 'factory_displayname', 'factory_displayname', '', 'center', '80', '0', '0', '1');
INSERT INTO `bh_grid_column` VALUES ('KnowledLib_KnowledTestCase', '平台名称', 'set_displayname', 'set_displayname', '', 'center', '80', '0', '0', '2');
INSERT INTO `bh_grid_column` VALUES ('KnowledLib_KnowledTestCase', '系统名称', 'systemname', 'systemname', '', 'center', '80', '0', '0', '3');
INSERT INTO `bh_grid_column` VALUES ('KnowledLib_KnowledTestCase', '设备类型', 'machine_type', 'machine_type', '', 'center', '80', '0', '0', '4');
INSERT INTO `bh_grid_column` VALUES ('KnowledLib_KnowledTestCase', '压力容器(管线)编号', 'plant_displayid', 'plant_displayid', '', 'center', '75', '0', '0', '5');
INSERT INTO `bh_grid_column` VALUES ('KnowledLib_KnowledTestCase', '压力容器(管线)名称', 'plant_displayname', 'plant_displayname', '', 'center', '75', '0', '0', '6');
INSERT INTO `bh_grid_column` VALUES ('KnowledLib_KnowledTestCase', '检验案例描述', 'describe_case', 'describe_case', '', 'center', '80', '0', '0', '7');
INSERT INTO `bh_grid_column` VALUES ('KnowledLib_KnowledTestCase', '记录人', 'recordusername', 'recordusername', '', 'center', '80', '0', '0', '8');
INSERT INTO `bh_grid_column` VALUES ('KnowledLib_KnowledTestCase', '记录日期', 'recordtime', 'recordtime', '', 'center', '80', '0', '0', '9');
INSERT INTO `bh_grid_column` VALUES ('KnowledLib_KnowledTestCase', '投用日期', 'use_time', 'use_time', '', 'center', '80', '1', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('CorrosionCoupon_Jqgrid', 'plantmatchkey', 'plantmatchkey', '', '', 'center', '80', '1', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('CorrosionCoupon_Jqgrid', '油田名称', 'factory_displayname', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('CorrosionCoupon_Jqgrid', '平台名称', 'set_displayname', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('CorrosionCoupon_Jqgrid', '监测位置', 'tablet_position', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('CorrosionCoupon_Jqgrid', '挂片编号', 'tablet_num', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('CorrosionCoupon_Jqgrid', '关联设备', 'plant_displayname', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('CorrosionCoupon_Jqgrid', '均匀腐蚀速率(mm/y)', 'average_rate', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('CorrosionCoupon_Jqgrid', '局部腐蚀速率(mm/y)', 'local_rate', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('CorrosionCoupon_Jqgrid', '局部最大腐蚀速率(mm/y)', 'max_rate', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('CorrosionCoupon_Jqgrid', '腐蚀等级', 'corrosion_grade', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('CorrosionCoupon_Jqgrid', '结论', 'conclusion', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('CorrosionCoupon_Jqgrid', '记录人', 'entry_people', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('CorrosionCoupon_Jqgrid', '记录日期', 'entry_time', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('ChemicalReagent_Jqgrid', '油田名称', 'factory_displayname', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('ChemicalReagent_Jqgrid', '平台名称', 'set_displayname', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('ChemicalReagent_Jqgrid', '注入点', 'fill_point', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('ChemicalReagent_Jqgrid', '化学药剂类型', 'chemical_class', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('ChemicalReagent_Jqgrid', '化学药剂编号', 'chemical_num', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('ChemicalReagent_Jqgrid', '化学药剂名称', 'chemical_name', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('ChemicalReagent_Jqgrid', '型号', 'chemical_model', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('ChemicalReagent_Jqgrid', '浓度(mg/L)', 'chemical_concentration', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('ChemicalReagent_Jqgrid', '凝固点(℃)', 'chemical_solid', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('ChemicalReagent_Jqgrid', 'pH', 'chemical_PH', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('ChemicalReagent_Jqgrid', '密度(kg/m3)', 'chemical_density', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('ChemicalReagent_Jqgrid', '加注方式', 'fill_way', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('ChemicalReagent_Jqgrid', '加注周期', 'fill_cycle', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('ChemicalReagent_Jqgrid', '加注量', 'fill_amount', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('ChemicalReagent_Jqgrid', '缓蚀率(%)', 'corrosion_rate', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('ChemicalReagent_Jqgrid', '注入日期', 'fill_time', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('ChemicalReagent_Jqgrid', '记录人', 'record_user', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('ChemicalReagent_Jqgrid', '记录日期', 'record_time', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('ThicknessMeasurement_Jqgrid', '油田名称', '', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('ThicknessMeasurement_Jqgrid', '平台名称', '', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('ThicknessMeasurement_Jqgrid', '系统名称', '', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('ThicknessMeasurement_Jqgrid', '设备类型', '', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('ThicknessMeasurement_Jqgrid', '压力容器(管线)', '', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('ThicknessMeasurement_Jqgrid', '检验日期', '', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('ThicknessMeasurement_Jqgrid', '记录人', '', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('ThicknessMeasurement_Jqgrid', '记录日期', '', '', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('AccidentInfo_modifyInfo', '油田名称', 'factory_displayname', 'factory_displayname', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('AccidentInfo_modifyInfo', '平台名称', 'set_displayname', 'set_displayname', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('AccidentInfo_modifyInfo', '系统名称', 'systemname', 'systemname', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('AccidentInfo_modifyInfo', '设备类型', 'machine_type', 'machine_type', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('AccidentInfo_modifyInfo', '压力容器(管线)编号', 'plant_displayid', 'plant_displayid', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('AccidentInfo_modifyInfo', '压力容器(管线)名称', 'plant_displayname', 'plant_displayname', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('AccidentInfo_modifyInfo', '字段名称', 'colume_name', 'colume_name', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('AccidentInfo_modifyInfo', '修改前', 'before_modify', 'before_modify', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('AccidentInfo_modifyInfo', '修改后', 'after_modify', 'after_modify', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('AccidentInfo_modifyInfo', '记录人', 'recordusername', 'recordusername', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('AccidentInfo_modifyInfo', '记录日期', 'recordtime', 'recordtime', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('RunManage_AccidentInfo', '记录id', 'accident_id', 'accident_id', '', 'center', '80', '1', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('RunManage_AccidentInfo', 'plantmatchkey', 'plantmatchkey', 'plantmatchkey', '', 'center', '80', '1', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('RunManage_AccidentInfo', '油田名称', 'factory_displayname', 'factory_displayname', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('RunManage_AccidentInfo', '平台名称', 'set_displayname', 'set_displayname', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('RunManage_AccidentInfo', '系统名称', 'systemname', 'systemname', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('RunManage_AccidentInfo', '设备类型', 'machine_type', 'machine_type', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('RunManage_AccidentInfo', '压力容器(管线)编号', 'plant_displayid', 'plant_displayid', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('RunManage_AccidentInfo', '压力管线(管线)名称', 'plant_displayname', 'plant_displayname', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('RunManage_AccidentInfo', '投用日期', 'use_time', 'use_time', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('RunManage_AccidentInfo', '事故描述', 'consequence_analyse', 'consequence_analyse', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('RunManage_AccidentInfo', '记录人', 'recordusername', 'recordusername', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('RunManage_AccidentInfo', '创建日期', 'createtime', 'createtime', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('RunManage_AccidentInfo', '记录日期', 'recordtime', 'recordtime', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Pipe_ChangeInfo_modifyInfo', '油田名称', 'factory_displayname', 'factory_displayname', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Pipe_ChangeInfo_modifyInfo', '平台名称', 'set_displayname', 'set_displayname', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Pipe_ChangeInfo_modifyInfo', '系统名称', 'systemname', 'systemname', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Pipe_ChangeInfo_modifyInfo', '设备类型', 'machine_type', 'machine_type', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Pipe_ChangeInfo_modifyInfo', '压力容器(管线)编号', 'plant_displayid', 'plant_displayid', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Pipe_ChangeInfo_modifyInfo', '压力容器(管线)名称', 'plant_displayname', 'plant_displayname', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Pipe_ChangeInfo_modifyInfo', '字段名称', 'colume_name', 'colume_name', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Pipe_ChangeInfo_modifyInfo', '修改前', 'before_modify', 'before_modify', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Pipe_ChangeInfo_modifyInfo', '修改后', 'after_modify', 'after_modify', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Pipe_ChangeInfo_modifyInfo', '记录人', 'recordusername', 'recordusername', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Pipe_ChangeInfo_modifyInfo', '记录日期', 'recordtime', 'recordtime', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Pipe_ChangeInfo_modifyInfo', '记录id', 'change_id', 'change_id', '', 'center', '80', '1', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_SafeAttachment', 'safe_id', 'safe_id', 'safe_id', '', 'center', '50', '1', '0', '1');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_SafeAttachment', '油田名称', 'factory_displayname', 'factory_displayname', '', 'center', '50', '1', '0', '2');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_SafeAttachment', '平台名称', 'set_displayname', 'set_displayname', '', 'center', '50', '1', '0', '3');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_SafeAttachment', '系统名称', 'systemname', 'systemname', '', 'center', '50', '1', '0', '4');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_SafeAttachment', '设备类型', 'machine_type', 'machine_type', '', 'center', '50', '1', '0', '5');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_SafeAttachment', '压力容器编号', 'plant_displayid', 'plant_displayid', '', 'center', '50', '1', '0', '6');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_SafeAttachment', '压力容器名称', 'plant_displayname', 'plant_displayname', '', 'center', '50', '1', '0', '7');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_SafeAttachment', '安全附件分类', 'safe_class', 'safe_class', '', 'center', '50', '0', '0', '8');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_SafeAttachment', '安全附件编号', 'safe_num', 'safe_num', '', 'center', '50', '1', '0', '9');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_SafeAttachment', '安全附件名称', 'safe_name', 'safe_name', '', 'center', '50', '0', '0', '10');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_SafeAttachment', '安装位置', 'installposition', 'installposition', '', 'center', '50', '0', '0', '11');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_SafeAttachment', '型号', 'model', 'model', '', 'center', '50', '0', '0', '12');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_SafeAttachment', '数量', 'count', 'count', '', 'center', '50', '0', '0', '13');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_SafeAttachment', '投用日期', 'usetime', 'usetime', '', 'center', '50', '0', '0', '14');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_SafeAttachment', '下次检验日期', 'nextinspectiondate', 'nextinspectiondate', '', 'center', '50', '0', '0', '15');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_SafeAttachment', '记录日期', 'recordtime', 'recordtime', '', 'center', '50', '0', '0', '16');
INSERT INTO `bh_grid_column` VALUES ('UnitInfo_BasicUnitInfo', '创建日期', 'createtime', 'createtime', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Container_ChangeInfo_modifyInfo', '油田名称', 'factory_displayname', 'factory_displayname', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Container_ChangeInfo_modifyInfo', '平台名称', 'set_displayname', 'set_displayname', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Container_ChangeInfo_modifyInfo', '系统名称', 'systemname', 'systemname', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Container_ChangeInfo_modifyInfo', '设备类型', 'machine_type', 'machine_type', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Container_ChangeInfo_modifyInfo', '压力容器(管线)编号', 'plant_displayid', 'plant_displayid', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Container_ChangeInfo_modifyInfo', '压力容器(管线)名称', 'plant_displayname', 'plant_displayname', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Container_ChangeInfo_modifyInfo', '字段名称', 'colume_name', 'colume_name', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Container_ChangeInfo_modifyInfo', '修改前', 'before_modify', 'before_modify', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Container_ChangeInfo_modifyInfo', '修改后', 'after_modify', 'after_modify', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Container_ChangeInfo_modifyInfo', '记录人', 'recordusername', 'recordusername', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Container_ChangeInfo_modifyInfo', '记录日期', 'recordtime', 'recordtime', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Container_ChangeInfo_modifyInfo', '记录id', 'change_id', 'change_id', '', 'center', '80', '1', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Runstate', '油田名称', 'factory_displayname', 'factory_displayname', '', 'center', '80', '0', '0', '1');
INSERT INTO `bh_grid_column` VALUES ('Runstate', '平台名称', 'set_displayname', 'set_displayname', '', 'center', '80', '0', '0', '2');
INSERT INTO `bh_grid_column` VALUES ('Runstate', '运行状态', 'runstate', 'runstate', '', 'center', '80', '0', '0', '3');
INSERT INTO `bh_grid_column` VALUES ('Runstate', '记录人', 'record_username', 'record_username', '', 'center', '50', '0', '0', '4');
INSERT INTO `bh_grid_column` VALUES ('Runstate', '记录日期', 'record_time', 'record_time', '', 'center', '50', '0', '0', '5');
INSERT INTO `bh_grid_column` VALUES ('Container_ChangeInfo', 'plantmatchkey', 'plantmatchkey', 'plantmatchkey', '', 'center', '80', '1', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Container_ChangeInfo', '记录id', 'change_id', 'change_id', '', 'center', '80', '1', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Container_ChangeInfo', '油田名称', 'factory_displayname', 'factory_displayname', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Container_ChangeInfo', '平台名称', 'set_displayname', 'set_displayname', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Container_ChangeInfo', '系统名称', 'systemname', 'systemname', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Container_ChangeInfo', '设备类型', 'machine_type', 'machine_type', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Container_ChangeInfo', '设备(管线)编号', 'plant_displayid', 'plant_displayid', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Container_ChangeInfo', '设备(管线)名称', 'plant_displayname', 'plant_displayname', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Container_ChangeInfo', '投用日期', 'use_time', 'use_time', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Container_ChangeInfo', '变动描述', 'change_remark', 'consequence_analyse', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Container_ChangeInfo', '变动方式', 'change_way', 'change_way', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Container_ChangeInfo', '变动日期', 'change_time', 'change_time', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Container_ChangeInfo', '变动主要项目', 'change_main', 'change_main', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Container_ChangeInfo', '变动承担单位', 'change_unit', 'change_unit', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Container_ChangeInfo', '变动承担单位代码', 'change_unit_num', 'change_unit_num', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Container_ChangeInfo', '创建日期', 'createtime', 'createtime', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Container_ChangeInfo', '记录人', 'recordusername', 'recordusername', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Container_ChangeInfo', '记录日期', 'recordtime', 'recordtime', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Pipe_ChangeInfo', 'change_id', 'change_id', 'change_id', '', 'cen', '80', '1', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Pipe_ChangeInfo', 'plantmatchkey', 'plantmatchkey', 'plantmatchkey', '', 'center', '80', '1', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Pipe_ChangeInfo', '油田名称', 'factory_displayname', 'factory_displayname', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Pipe_ChangeInfo', '平台名称', 'set_displayname', 'set_displayname', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Pipe_ChangeInfo', '系统名称', 'systemname', 'systemname', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Pipe_ChangeInfo', '设备类型', 'machine_type', 'machine_type', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Pipe_ChangeInfo', '设备(管线)编号', 'plant_displayid', 'plant_displayid', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Pipe_ChangeInfo', '设备(管线)名称', 'plant_displayname', 'plant_displayname', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Pipe_ChangeInfo', '投用日期', 'use_time', 'use_time', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Pipe_ChangeInfo', '返修描述', 'change_remark', 'change_remark', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Pipe_ChangeInfo', '返修日期', 'change_time', 'change_time', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Pipe_ChangeInfo', '返修原因', 'change_reason', 'change_reason', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Pipe_ChangeInfo', '返修单位', 'change_unit', 'change_unit', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Pipe_ChangeInfo', '返修单位代码', 'change_unit_num', 'change_unit_num', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Pipe_ChangeInfo', '返修内容', 'change_main', 'change_main', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Pipe_ChangeInfo', '创建日期', 'createtime', 'createtime', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Pipe_ChangeInfo', '记录人', 'recordusername', 'recordusername', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('Pipe_ChangeInfo', '记录日期', 'recordtime', 'recordtime', '', 'center', '80', '0', '0', '0');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBI', 'plantmatchkey', 'plantmatchkey', 'plantmatchkey', '', 'center', '50', '1', '0', '1');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBI', 'public_id', 'public_id', 'public_id', '', 'center', '50', '1', '0', '1');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBI', 'id_type', 'id_type', 'id_type', '', 'center', '50', '1', '0', '1');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBI', '油田名称', 'factory_displayname', 'factory_displayname', '', 'center', '50', '0', '0', '2');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBI', '平台名称', 'set_displayname', 'set_displayname', '', 'center', '50', '0', '0', '3');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBI', '系统名称', 'systemname', 'systemname', '', 'center', '50', '0', '0', '4');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBI', '设备类型', 'machine_type', 'machine_type', '', 'center', '50', '0', '0', '5');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBI', '压力容器(管线)编号', 'plant_displayid', 'plant_displayid', '', 'center', '75', '0', '0', '6');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBI', '压力容器(管线)名称', 'plant_displayname', 'plant_displayname', '', 'center', '75', '0', '0', '7');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBI', '部位分类', 'place_class', 'place_class', '', 'center', '50', '0', '0', '8');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBI', '部位编号', 'place_num', 'place_num', '', 'center', '50', '0', '0', '9');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBI', '部位名称', 'place_name', 'place_name', '', 'center', '50', '0', '0', '10');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBI', '腐蚀机理', 'corrosion_mechanism', 'corrosion_mechanism', '', 'center', '50', '0', '0', '11');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBI', '安全风险等级', 'grade_risk', 'grade_risk', '', 'center', '75', '0', '0', '12');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBI', '环境风险等级', 'environment_risk', 'environment_risk', '', 'center', '75', '0', '0', '13');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBI', '经济风险等级', 'economy_risk', 'economy_risk', '', 'center', '75', '0', '0', '14');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBI', '记录人', 'record_person', 'record_person', '', 'center', '50', '0', '0', '15');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBI', '更新日期', 'record_time', 'record_time', '', 'center', '50', '0', '0', '16');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBIHistory', 'plantmatchkey', 'plantmatchkey', 'plantmatchkey', '', 'center', '50', '1', '0', '1');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBIHistory', 'public_id', 'public_id', 'public_id', '', 'center', '50', '1', '0', '1');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBIHistory', 'id_type', 'id_type', 'id_type', '', 'center', '50', '1', '0', '1');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBIHistory', '油田名称', 'factory_displayname', 'factory_displayname', '', 'center', '50', '0', '0', '2');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBIHistory', '平台名称', 'set_displayname', 'set_displayname', '', 'center', '50', '0', '0', '3');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBIHistory', '系统名称', 'systemname', 'systemname', '', 'center', '50', '0', '0', '4');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBIHistory', '设备类型', 'machine_type', 'machine_type', '', 'center', '50', '0', '0', '5');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBIHistory', '压力容器(管线)编号', 'plant_displayid', 'plant_displayid', '', 'center', '70', '0', '0', '6');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBIHistory', '压力容器(管线)名称', 'plant_displayname', 'plant_displayname', '', 'center', '70', '0', '0', '7');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBIHistory', '部位分类', 'place_class', 'place_class', '', 'center', '50', '0', '0', '8');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBIHistory', '部位编号', 'place_num', 'place_num', '', 'center', '50', '0', '0', '9');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBIHistory', '部位名称', 'place_name', 'place_name', '', 'center', '50', '0', '0', '10');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBIHistory', '腐蚀机理', 'corrosion_mechanism', 'corrosion_mechanism', '', 'center', '50', '0', '0', '11');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBIHistory', '腐蚀机理', 'corrosion_mechanism', 'corrosion_mechanism', '', 'center', '50', '0', '0', '11');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBIHistory', '安全风险等级', 'grade_risk', 'grade_risk', '', 'center', '70', '0', '0', '12');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBIHistory', '环境风险等级', 'environment_risk', 'environment_risk', '', 'center', '70', '0', '0', '13');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBIHistory', '经济风险等级', 'economy_risk', 'economy_risk', '', 'center', '70', '0', '0', '14');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBIHistory', '记录人', 'record_person', 'record_person', '', 'center', '50', '0', '0', '15');
INSERT INTO `bh_grid_column` VALUES ('KnowledForRBIHistory', '更新日期', 'record_time', 'record_time', '', 'center', '50', '0', '0', '16');
INSERT INTO `bh_grid_column` VALUES ('ThresholdSetting', 'plantmatchkey', 'plantmatchkey', 'plantmatchkey', '', 'center', '50', '1', '0', '1');
INSERT INTO `bh_grid_column` VALUES ('ThresholdSetting', '油田名称', 'factory_displayname', 'factory_displayname', '', 'center', '50', '0', '0', '2');
INSERT INTO `bh_grid_column` VALUES ('ThresholdSetting', '平台名称', 'set_displayname', 'set_displayname', '', 'center', '50', '0', '0', '3');
INSERT INTO `bh_grid_column` VALUES ('ThresholdSetting', '系统名称', 'systemname', 'systemname', '', 'center', '50', '0', '0', '4');
INSERT INTO `bh_grid_column` VALUES ('ThresholdSetting', '设备类型', 'machine_type', 'machine_type', '', 'center', '50', '0', '0', '5');
INSERT INTO `bh_grid_column` VALUES ('ThresholdSetting', '设备(管线)编号', 'plant_displayid', 'plant_displayid', '', 'center', '50', '0', '0', '6');
INSERT INTO `bh_grid_column` VALUES ('ThresholdSetting', '设备(管线)名称', 'plant_displayname', 'plant_displayname', '', 'center', '50', '0', '0', '7');
INSERT INTO `bh_grid_column` VALUES ('ThresholdSetting', '记录人', 'threshold_record_username', 'record_person', '', 'center', '50', '0', '0', '8');
INSERT INTO `bh_grid_column` VALUES ('ThresholdSetting', '记录日期', 'threshold_record_time', 'record_time', '', 'center', '50', '0', '0', '9');
INSERT INTO `bh_grid_column` VALUES ('ThresholdSetting_repair', 'plantmatchkey', 'plantmatchkey', 'plantmatchkey', '', 'center', '50', '1', '0', '1');
INSERT INTO `bh_grid_column` VALUES ('ThresholdSetting_repair', '油田名称', 'factory_displayname', 'factory_displayname', '', 'center', '50', '0', '0', '2');
INSERT INTO `bh_grid_column` VALUES ('ThresholdSetting_repair', '平台名称', 'set_displayname', 'set_displayname', '', 'center', '50', '0', '0', '3');
INSERT INTO `bh_grid_column` VALUES ('ThresholdSetting_repair', '系统名称', 'systemname', 'systemname', '', 'center', '50', '0', '0', '4');
INSERT INTO `bh_grid_column` VALUES ('ThresholdSetting_repair', '设备类型', 'machine_type', 'machine_type', '', 'center', '50', '0', '0', '5');
INSERT INTO `bh_grid_column` VALUES ('ThresholdSetting_repair', '设备(管线)编号', 'plant_displayid', 'plant_displayid', '', 'center', '50', '0', '0', '6');
INSERT INTO `bh_grid_column` VALUES ('ThresholdSetting_repair', '设备(管线)名称', 'plant_displayname', 'plant_displayname', '', 'center', '50', '0', '0', '7');
INSERT INTO `bh_grid_column` VALUES ('ThresholdSetting_repair', '字段名称', 'colume_name', 'colume_name', '', 'center', '50', '0', '0', '8');
INSERT INTO `bh_grid_column` VALUES ('ThresholdSetting_repair', '修改前', 'before_modify', 'before_modify', '', 'center', '50', '0', '0', '9');
INSERT INTO `bh_grid_column` VALUES ('ThresholdSetting_repair', '修改后', 'after_modify', 'after_modify', '', 'center', '50', '0', '0', '10');
INSERT INTO `bh_grid_column` VALUES ('ThresholdSetting_repair', '修改人', 'recordusername', 'recordusername', '', 'center', '50', '0', '0', '11');
INSERT INTO `bh_grid_column` VALUES ('ThresholdSetting_repair', '修改日期', 'recordtime', 'recordtime', '', 'center', '50', '0', '0', '12');
INSERT INTO `bh_grid_column` VALUES ('KnowledStandard', 'standard_id', 'standard_id', 'standard_id', '', 'center', '50', '1', '0', '1');
INSERT INTO `bh_grid_column` VALUES ('KnowledStandard', '设备类型', 'plant_type_desc', 'plant_type_desc', '', 'center', '50', '0', '0', '2');
INSERT INTO `bh_grid_column` VALUES ('KnowledStandard', '部位分类', 'place_type_desc', 'place_type_desc', '', 'center', '50', '0', '0', '3');
INSERT INTO `bh_grid_column` VALUES ('KnowledStandard', '腐蚀机理', 'corrosion_mechanism', 'corrosion_mechanism', '', 'center', '50', '0', '0', '4');
INSERT INTO `bh_grid_column` VALUES ('KnowledStandard', '检验方法', 'check_way', 'check_way', '', 'center', '50', '0', '0', '5');
INSERT INTO `bh_grid_column` VALUES ('KnowledStandard', '检验有效性', 'is_effective', 'is_effective', '', 'center', '50', '0', '0', '6');
INSERT INTO `bh_grid_column` VALUES ('KnowledStandard', '检验内容', 'check_content', 'check_content', '', 'center', '50', '0', '0', '7');
INSERT INTO `bh_grid_column` VALUES ('KnowledStandard', '检验周期', 'check_cycle', 'check_cycle', '', 'center', '50', '0', '0', '8');
INSERT INTO `bh_grid_column` VALUES ('KnowledStandard', '参考标准', 'reference_standard', 'reference_standard', '', 'center', '50', '0', '0', '9');
INSERT INTO `bh_grid_column` VALUES ('KnowledStandard', '记录日期', 'record_time', 'record_time', '', 'center', '50', '0', '0', '10');
INSERT INTO `bh_grid_column` VALUES ('AnalysisForOil', 'oil_id', 'oil_id', 'oil_id', '', 'center', '50', '1', '0', '1');
INSERT INTO `bh_grid_column` VALUES ('AnalysisForOil', '油田名称', 'factory_displayname', 'factory_displayname', '', 'center', '50', '0', '0', '2');
INSERT INTO `bh_grid_column` VALUES ('AnalysisForOil', '平台名称', 'set_displayname', 'set_displayname', '', 'center', '50', '0', '0', '3');
INSERT INTO `bh_grid_column` VALUES ('AnalysisForOil', '取样点位置', 'sample_position', 'sample_position', '', 'center', '50', '0', '0', '4');
INSERT INTO `bh_grid_column` VALUES ('AnalysisForOil', '取样日期', 'sample_time', 'sample_time', '', 'center', '50', '0', '0', '5');
INSERT INTO `bh_grid_column` VALUES ('AnalysisForOil', '流体代号', 'fluid_code', 'fluid_code', '', 'center', '50', '0', '0', '6');
INSERT INTO `bh_grid_column` VALUES ('AnalysisForOil', '流体名称', 'fluid_name', 'fluid_name', '', 'center', '50', '0', '0', '7');
INSERT INTO `bh_grid_column` VALUES ('AnalysisForOil', '代表性流体', 'fluid_deputy', 'fluid_deputy', '', 'center', '50', '0', '0', '8');
INSERT INTO `bh_grid_column` VALUES ('AnalysisForOil', '流体密度(kg/m<sup>3</sup>)', 'fluid_density', 'fluid_density', '', 'center', '70', '0', '0', '9');
INSERT INTO `bh_grid_column` VALUES ('AnalysisForOil', '记录人', 'record_username', 'record_username', '', 'center', '50', '0', '0', '10');
INSERT INTO `bh_grid_column` VALUES ('AnalysisForOil', '记录日期', 'record_time', 'record_time', '', 'center', '50', '0', '0', '11');
